on:
  push:
permissions:
  contents: write
#env:
#  GITHUB_CONTEX: ${{ toJson(github) }}
jobs:
  file:
    runs-on: ubuntu-latest #public
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - run: sudo apt update && sudo apt install -y clang libclang-dev autoconf m4 jq curl
    #- run: find /usr/lib/llvm-* -type d -name clang-c
    #- run: find /usr/lib/llvm-* -name libclang.so
    - name: foreign.scm
      run: |
        find /usr/lib/llvm-* -type d -name clang-c -exec ln -sfT {}/.. ./usr \;
        find /usr/lib/llvm-* -name libclang.so -exec ln -sf {} ./lib/. \;
        clang -o foreign -I./usr/. -L./lib/. -lclang 2src/foreign.c
        ./foreign 2src/yaml.h 1>include/foreign.scm
    - name: config.h
      run: ./bootstrap && ./configure
      working-directory: ./src/libyaml
    - run: mv ./src/libyaml/include/config.h ./include/.
    - name: static libyaml.egg
      if: 'github.event.repository.fork'
      run: |
        ./2src/m42egg.sh \
          -Dm4_author="riku-ri" \
          -Dm4_license="MIT" \
        <.libyaml.egg.m4 | tee libyaml.egg
        test -s libyaml.egg
    - name: libyaml.egg
      if: '!github.event.repository.fork'
      run: |
        ./2src/m42egg.sh \
          -Dm4_author="${{ github.repository_owner }}" \
          -Dm4_license=${{ github.event.repository.license.spdx_id }} \
        <.libyaml.egg.m4 | tee libyaml.egg
        test -s libyaml.egg
    - name: LICENSE
      if: '!github.event.repository.fork'
      run: |
        m4 -P \
          -Dm4_year="$(date +%Y)" \
          -Dm4_name="${{ github.repository_owner }}" \
        <.LICENSE.m4 | tee LICENSE
        test -s LICENSE
    - name: libyaml.scm.release-info
      run: |
        m4 -P \
          -Dm4_release="$(curl -L https://api.github.com/repos/riku-ri/libyaml.scm/releases | jq '.[].name' | xargs -n1 cut -b2- | xargs -I__ echo "(release \"__\")")" \
        <.libyaml.release-info.m4 | tee libyaml.release-info
        test -s libyaml.release-info
    - run: git status
    - run: git diff .
    - name: diff and push
      run: |
        git config user.name "run#${{ github.run_id }}"
        git config user.email "run#${{ github.run_id }}@action.github.com"
        git add include/foreign.scm
        git add include/config.h
        git add libyaml.egg
        git add LICENSE
        git add libyaml.scm.release-info
        git diff-index --quiet HEAD || ( git commit -m '[auto][from github action][include/foreign.scm]' && git pull && git push https://${{ secrets.AUTO_PUSH }}@github.com/${{ github.event.repository.full_name }} -f )
